5명의 학생의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.

1. 학생 이름을 나타내는 열을 포함시키지 않고 데이터프레임 `df_score1` 을 생성한 후,   
`df_score1.index` 속성에 학생 이름을 나타내는 열을 지정하여 인덱스를 지정한다.    
`reset_index` 명령으로 이 인덱스 열을 명령으로 일반 데이터열로 바꾸여 데이터프레임 `df_score2`을 만든다.
2. 학생 이름을 나타내는 열이 일반 데이터 열을 포함하는 데이터프레임 `df_score2`에 `set_index` 명령을 적용하여 다시 학생 이름을 나타내는 열을 인덱스로 변경한다.

In [1]:
import pandas as pd
import numpy as np

In [12]:
score = np.random.randint(0,101,(5,3))
score

array([[61, 76, 81],
       [55, 36, 75],
       [ 6, 85, 90],
       [95, 51, 81],
       [85, 23, 57]])

In [17]:
df_score1 = pd.DataFrame(score, columns = ['국어','영어','수학'])
df_score1

국어  영어  수학
0  61  76  81
1  55  36  75
2   6  85  90
3  95  51  81
4  85  23  57

In [19]:
df_score1.index = ['s1','s2','s3','s4','s5']
df_score1

국어  영어  수학
s1  61  76  81
s2  55  36  75
s3   6  85  90
s4  95  51  81
s5  85  23  57

In [21]:
df_score2 = df_score1.reset_index()
df_score2

index  국어  영어  수학
0    s1  61  76  81
1    s2  55  36  75
2    s3   6  85  90
3    s4  95  51  81
4    s5  85  23  57

In [22]:
df_score2 = df_score2.set_index('index')
df_score2

국어  영어  수학
index            
s1     61  76  81
s2     55  36  75
s3      6  85  90
s4     95  51  81
s5     85  23  57

A 반 학생 5명과 B반 학생 5명의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.

1. "반", "번호", "국어", "영어", "수학" 을 열로 가지는 데이터프레임 `df_score3`을 만든다.

2. `df_score3`을 변형하여 1차 행 인덱스로 "반"을 2차 행 인덱스로 "번호"을 가지는 데이터프레임 `df_score4`을 만든다.

3. 데이터 프레임 `df_score4`에 각 학생의 평균을 나타내는 행을 오른쪽에 추가한다.

4. `df_score3`을 변형하여 행 인덱스로 "번호"를, 1차 열 인덱스로 "국어", "영어", "수학"을, 2차 열 인덱스로 "반"을 가지는 데이터프레임 `df_score5`을 만든다.

5. 데이터 프레임 `df_score5`에 각 반별 각 과목의 평균을 나타내는 행을 아래에 추가한다.

In [38]:
np.random.seed(0)
class1 = np.array(list('AAAAABBBBB')).reshape(10,1)
class1

array([['A'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['B']], dtype='<U1')

In [36]:
score = np.random.randint(0,101,(10,3))
score

array([[57, 89, 96],
       [93, 49, 71],
       [97, 29,  4],
       [30, 62, 17],
       [91, 19, 53],
       [27,  3, 66],
       [ 8, 53, 47],
       [85, 57, 49],
       [13, 91, 22],
       [77, 86, 43]])

In [39]:
number = np.random.choice(range(1,6),5, replace=False)
number

array([3, 1, 2, 4, 5])

In [40]:
number = np.hstack([number, number]).reshape(10,1)
number

array([[3],
       [1],
       [2],
       [4],
       [5],
       [3],
       [1],
       [2],
       [4],
       [5]])

In [42]:
df_score3 = pd.DataFrame(np.hstack([class1,number,score]),
                         columns=["반","번호","국어","영어","수학"])
df_score3

반 번호  국어  영어  수학
0  A  3  57  89  96
1  A  1  93  49  71
2  A  2  97  29   4
3  A  4  30  62  17
4  A  5  91  19  53
5  B  3  27   3  66
6  B  1   8  53  47
7  B  2  85  57  49
8  B  4  13  91  22
9  B  5  77  86  43

In [47]:
#2 


ValueError: Length of new names must be 1, got 2