In [ ]:
# # 주피터노트북 셀 스타일 조절
# from IPython.core.display import display, HTML
# # display(HTML("<style>.container { font-weight: bold !important; }</style>"))
# display(HTML("<style>.container { width: 100% !important; }</style>"))

# # 경고메시지 숨기기
# import warning
# warnings.filterwarnings(action='ignore')

# Numpy 개요
Numeric + Python = Numpy
수학 및 과학 연산을 위한 파이썬 패키지
배열이나 행렬 계산에 용이한 메서드를 제공
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
관련 사이트 : http://www.numpy.org
일반 List에 비해 빠르고, 메모리 효율적

반복문 없이 데이터 배열에 대한 처리를 지원함
선형대수와 관련된 다양한 기능을 제공함
Reference Site
cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS
설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy

In [3]:
import numpy as np
np.__version__  #__매직메서드__

'1.26.4'

## 넘파이 배열 이해하기
ndim(dimention, rank)
몇차원인지 반환

In [2]:
a = np.array(0)
a, a.ndim , type(a) #scarlar??

(array(0), 0, numpy.ndarray)

In [4]:
a= np.array([2,4,6])
a, a.ndim, type(a)  #1이라고 찍힌이유 : 차원이라서

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a= [[1,2,3],[4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [7]:
a = np.array([[1,2,3],[4,5,6]])
a, a.ndim, type(a) 

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [8]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a, a.ndim, type(a) #2차원이 두개 = 3차원 (두겹이됨)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [9]:
a.shape #array에서만 쓸 수 있는 메서드 
#2행 3열이 두개가 있어 

(2, 2, 3)

In [10]:
a.shape?

Type:        tuple
String form: (2, 2, 3)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

## shape
행렬의 차원으로, 몇행 몇열인지 반환

In [11]:
a = np.array(3)
a, a.shape #a.shape안나옴 => 행렬아니기때문

(array(3), ())

In [12]:
a = np.array([1,3,5,7,9])
a, a.shape #튜플로 5개요소 들어있습니다 

(array([1, 3, 5, 7, 9]), (5,))

In [13]:
a = np.array([[1,2,3],[4,5,6]])
a, a.shape #2행3열 (2,3)

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [14]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열=> 3차원

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## 넘파이 배열
리스트를 넘파이 배열로 생성 np.array(리스트)
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [15]:
# 1차원 리스트 객체 (iterable)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [16]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [17]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [18]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))          #사이즈=요소의 갯수 길이=행의 갯수 
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [19]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [20]:
# 길이가 달라 에러 리턴 = 연산할수없음
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [21]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 숫자계산 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [22]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [23]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [24]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype
https://numpy.org/doc/stable/reference/arrays.dtypes.html
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 
숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다뜻한다

In [25]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [26]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [28]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [29]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0]) #배열연산에서는 무한대로 표현해줌 

C:\Users\yoosj\AppData\Local\Temp\ipykernel_28316\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\yoosj\AppData\Local\Temp\ipykernel_28316\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [30]:
np.log(0)

C:\Users\yoosj\AppData\Local\Temp\ipykernel_28316\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [31]:
np.exp(-np.inf)  #exp = 지수

0.0

## 기술통계

In [32]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [33]:
x.mean() #평균 

4.8076923076923075

In [34]:
np.mean(x) #똑같음 np에 mean이라는 메소드, 데이터는 x야 

4.8076923076923075

In [35]:
np.var(x)  # 분산

115.23224852071006

In [36]:
np.std(x)  # 표준 편차

10.734628476137871

In [37]:
np.max(x)  # 최댓값

23

In [38]:
np.min(x)  # 최소값

-24

In [39]:
np.median(x)  # 중앙값

5.0

## 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [40]:
np.percentile(x, 0)  # 최소값 0%의값

-24.0

In [41]:
np.percentile(x, 25)  # 1사분위 수 25%에 있는 것 

0.0

In [42]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [43]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [44]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소

In [45]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 
#np.ones(10) 1 10개채워줘 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [46]:
print(np.ones((2,4)), np.ones((2,4)).dtype)
#2행 4열로 만들어줘

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [47]:
np.ones? #연산중 특징 유지하고 싶을 때

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [48]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

[1 1 1 1 1 1 1 1 1 1] int32


In [49]:
# 0으로 메모리 초기화 / 데이터 유지하고 싶지 않을 때
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [51]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [50]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.37962117e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]] float64
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.37962117e-306 1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 0.00000000e+000]]
[[         0          0 -489974960]
 [       555 -489974160        555]
 [-489972320        555 -419637504]]


In [52]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [53]:
# 1~20으로 구성된 4행 5열의 넘파이 배열 print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [54]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [55]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [56]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [58]:
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [59]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [61]:
#2차원으로 바꾸고 싶어! 10행 5열로 바꿔줘 
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [63]:
#5행 10열로 바꿔줘
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [65]:
# 2차원 -> 1차원  차원을 평평하게! flatten
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [66]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [68]:
#method chaining 
np.arange(2,101,2).reshape(5,10)

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [70]:
np.arange(1,31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [69]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [73]:
## quiz 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [77]:
np.arange(1, 21).reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
np.arange(1,101).reshape(-1,50)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [79]:
# 원본 값이 바뀜
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [13]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [14]:
# flatten
a.shape = -1
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

## 넘파이배열의 자료형 형변환
배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32

In [82]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [83]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [84]:
# 실수형, 3행 3열  dtype 지정 
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [85]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [86]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [87]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [88]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [89]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [90]:
# 문자열 숫자 => 정수 , 실수  제약있음 실제형과 맞아야함 
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [91]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [92]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

## 1D array

In [4]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [94]:
a[0]

1

In [95]:
a[4]

9

In [96]:
a[-1]

9

In [99]:
a[[0,2,4]]

array([1, 5, 9])

In [6]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b, b.ndim, b.shape

(array([[1, 3],
        [4, 2]]),
 2,
 (2, 2))

In [101]:
a[b]  #a[1] a[3] a[4] a[2] 

array([[3, 7],
       [9, 5]])

In [102]:
print (a)
a[2] = 0 
print(a)

[1 3 5 7 9]
[1 3 0 7 9]


In [105]:
a[1] += 2
a

array([1, 5, 0, 7, 9])

In [149]:
a[1] + 2 
a

array([1, 3, 5, 7, 9])

In [106]:
a[0] += 2
a

array([3, 5, 0, 7, 9])

## 2D array

In [107]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [108]:
# 2차원 인덱싱할 때, 값을 하나면 넣으면 행인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [109]:
a[1]

array([5, 6, 7, 8, 9])

In [110]:
# 값이 2개 들어가면, 행/열 인덱싱
a[0, 0]

0

In [112]:
a[2,1]

11

In [113]:
a[-1,-1]

14

In [119]:
a[-1][-1]

10

In [115]:
#값변경
a = np.arange(15).reshape(3,-1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [116]:
a[1] = [1,3,5,7,9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [117]:
a[-1] = 10 #전부10으로 채워짐
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [118]:
a[0] += [1,2,3,4,5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

## 넘파이배열 슬라이싱
1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원

넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

In [120]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [121]:
a[:]

array([1, 3, 5, 7, 9])

In [122]:
a[1:]

array([3, 5, 7, 9])

In [123]:
a[-1:]

array([9])

In [124]:
a[1:4]

array([3, 5, 7])

In [126]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
a[1::2]

array([1, 3, 5, 7, 9])

In [129]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2D array

In [130]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [131]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [132]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [133]:
a[:, :] #행의범위, 열의 범위

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [134]:
a[:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [137]:
a[:,-1:]

array([[14],
       [19],
       [24]])

In [143]:
a[1:,2:3]

array([[17],
       [22]])

In [144]:
a[:2,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [146]:
a[1,2]

17

In [1]:
import numpy as np

In [4]:
a = np.arange(10, 25).reshape(3, 5)

In [5]:
a[::-1] #행뒤집기

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [6]:
a[::,::-1] #열뒤집기 

array([[14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

## 전치행렬
넘파이배열.T : 행과 열 구조 변경
가로가 세로로 옮겨진다 

In [7]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# 2행 3열로 변환
print(matrix_d.T)

[[1 3 5]
 [2 4 6]]


In [9]:
# reshape과 transpose은 값이 다름을 유의
#reshape는 flatten이 선행됨 (1열로 펴고 다시 재구조화)
print(matrix_d.reshape(2,3)) 

[[1 2 3]
 [4 5 6]]


## 난수로 구성된 넘파이 배열
np.random.randint(start, end, n) : 정수 난수
np.random.randint(start, end, (i, j))

In [10]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

array([1, 9, 4, 4, 8, 5, 9, 9, 6, 1])

In [11]:
np.random.randint(1, 49, 6)

array([48, 18, 44, 18, 39, 37])

In [12]:
#2행 5열로 출력
np.random.randint(1, 10, (2,5))

array([[3, 5, 9, 9, 7],
       [7, 7, 3, 2, 7]])

## 섞기
np.random.shuffle(넘파이배열) 원본에 바로 적용

In [14]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.random.shuffle(matrix_e)
matrix_e

array([ 9,  5,  7, 10,  2,  1,  3,  6,  4,  8])

In [16]:
#Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

array([40, 13,  3, 19, 12, 42])

## 실수 난수
np.random.randn(n) np.random.randn(i, j)

In [17]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1 #값을 하나만 넣으면 갯수 10개 

array([-0.90242341,  0.21916797,  1.00418717, -1.3222537 , -2.65189716,
        1.32572403,  1.78864839,  0.11303133,  1.13353982, -1.15969932])

In [18]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-0.31806657, -0.70019367, -1.28409237, -0.38707781],
       [-0.1209076 , -1.11287682, -0.88415697, -1.44122877],
       [-1.06939887, -1.02393124,  0.03746315,  0.31586922],
       [ 0.61427235,  1.56110008, -0.75849407, -0.35020328]])

## 집계함수에서의 축
2차원에서의 집계합수(sum, mean)
axis = 0, 1
np.sum(넘파이배열, axis=0/1)
np.mean(넘파이배열, axis=0/1)
np.sort(넘파이배열, axis=0/1)

In [38]:
m1 = np.array([[26, 29,  3, 38, 32],
    [45, 18, 48, 33, 33],
    [37, 39,  1, 39, 46],
    [18, 39, 23,  5, 20],
    [44, 44, 45, 17, 39]])

In [20]:
np.sum(m1, axis=0) # (x)열합계  

array([170, 169, 120, 132, 170])

In [21]:
np.sum(m1, axis=1) #행합계

array([128, 177, 162, 105, 189])

In [26]:
# 1번째행의 합계는
np.sum(m1[2,:])

131

In [39]:
# 3번째 열 의 합계는
np.sum(m1[1:4,1:4], axis = 0) # x축(행 방향) 합계

array([96, 72, 77])

In [40]:
#4번째 행 합계
np.sum(m1[1:4,1:4], axis = 1)

array([99, 79, 67])

## np.sort()

In [42]:
# 정수 난수로 구성된 4x3
m2 = np.array([[42, 39, 32],
       [25, 20, 33],
       [29, 30, 42],
       [39,  2, 48]])
m2

array([[42, 39, 32],
       [25, 20, 33],
       [29, 30, 42],
       [39,  2, 48]])

In [25]:
np.sort(m2) #행안에서 열정렬 

array([[32, 39, 42],
       [20, 25, 33],
       [29, 30, 42],
       [ 2, 39, 48]])

In [32]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x0000012EF62C0720>
File:            c:\users\yoosj\anaconda3\lib\site-packages\numpy\core\fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of

In [26]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[25,  2, 32],
       [29, 20, 33],
       [39, 30, 42],
       [42, 39, 48]])

In [28]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다
#np.sort = +요소별 정렬 

array([[39,  2, 48],
       [29, 30, 42],
       [25, 20, 33],
       [42, 39, 32]])

In [43]:
m2[::, ::-1]

array([[32, 39, 42],
       [33, 20, 25],
       [42, 30, 29],
       [48,  2, 39]])

In [29]:
np.sort(m2, axis=1) # 열방향 오름차순

array([[32, 39, 42],
       [20, 25, 33],
       [29, 30, 42],
       [ 2, 39, 48]])

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [44]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

array([2, 1, 0], dtype=int64)

In [51]:
(x[np.argsort(x)]) # 인덱스값으로 실제 값 출력 

array([4, 5, 9])

In [50]:
print(x)

[9 5 4]


## 넘파이 배열 요소 추가와 삭제
삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)

In [52]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
len(m3)

10

In [34]:
np.insert(m3, 0, 100) #m3에 [0]에 100넣어줘

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [35]:
m3 #오리지널값이 변한게 아님 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [37]:
np.insert(m3, len(m3), 500) 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [55]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 차원축소해서 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [41]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [42]:
m4.shape, m4.shape[1], len(m4) #오리지널바뀐거 아님 여전히 3,3 

((3, 3), 3, 3)

In [43]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [44]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [57]:
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [59]:
print(m4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 배열 합치기
np.vstack((배열1,배열2....)) : 세로 합치기
np.hstack((배열1,배열2....)) : 가로 합치기
np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [60]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [49]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [50]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [51]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [52]:
f = np.concatenate((c,d), axis=1)
f, f.ndim, f.shape  # 밑에와 차이를 보세요오오 

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

In [54]:
np.hstack((a,b)),np.hstack((a,b)).ndim,np.hstack((a,b)).shape

(array([1, 2, 3, 4, 5, 6]), 1, (6,))

## boolean indexing, mask 중요!!!!

조건절의 결과는 True, False로 반환
True인 결과의 데이터 반환
넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [62]:
matrix = np.arange(1, 11)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
matrix > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
matrix[matrix > 5] #불린의 true값으로 다시 array

array([ 6,  7,  8,  9, 10])

In [65]:
(matrix > 5).sum() #true =1 이니까 합치면 10
#true인 항목 개수 세기 

5

In [66]:
m1 = np.random.randint(1, 100, 10)
m1

array([59, 84, 77, 92, 72, 72, 62, 78, 53, 18])

In [67]:
(m1 >30) & (m1 <70)

array([ True, False, False, False, False, False,  True, False,  True,
       False])

In [68]:
m1[(m1 >30) & (m1 <70)]

array([59, 62, 53])

In [74]:
# ~ 은 reverse를 의미 
m1[(m1 > 30) & ~(m1 < 70)]

array([84, 77, 92, 72, 72, 78])

In [77]:
m1[(m1<30) | (m1>70)]

array([84, 77, 92, 72, 72, 78, 18])

In [70]:
m2 = np.random.randint(1, 100, 10)
m2[(m2 < 10 ) | (m2 >90)] #겹치는게 없으니까 또는 | 으로 

array([92,  6,  3, 98])

## fancy indexing(filtering)
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]
넘파이배열2 : 인덱스 역할 (only 정수형)

In [83]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i] # => 위에 한거 리스트 덮기 

(array([87, 77, 67, 38, 92, 29, 20, 20, 25, 48, 81, 49, 76,  4, 25, 75, 39,
        30, 63, 39, 87,  4, 91, 71, 28, 30, 77, 69, 89, 36]),
 array([87, 67, 38, 81, 87]))

## np.where()를 이용한 필터링
np.where(조건식) : 조건식 만족하는 인덱스 반환
np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [78]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [79]:
np.where(a<5)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [85]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))